spring:
  application:
    name: subject
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
#    url: jdbc:mariadb://localhost:3306/testdb
#    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: 12341234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect